name: Label bugs

on:
  issues:
    types: [opened]

jobs:
  add-labels:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.body, 'New Trace collected:') == true
    steps:
      - name: Add labels
        uses: actions-cool/issues-helper@v2.2.1
        with:
          actions: 'add-labels'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          labels: 'bug'
      - name: Remove runs
        uses: GongT/cancel-previous-workflows@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DELETE: 'yes'
